version: '2'
services:
  web:
    build:
      context: .
      dockerfile: dockerfile-dev
    depends_on:
      - postgresql
    ports:
      - "8069:8069"
    environment:
      - ODOO_EMAIL=user@pappaya.com
      - ODOO_PASSWORD=pappaya
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=postgres
    volumes:
      - odoo-web-data:/bitnami/odoo
      - ./addons:/bitnami/odoo/addons
  postgresql:
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:
